Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2024-12, with the labels that each got.

#499 Update VanishChecker to 1.0.4
  settings.gradle.kts
Labels: dependencies

#501 Update messages_pl.yml
  even-more-fish-plugin/src/main/resources/locales/messages_pl.yml
Labels: translations

#502 Economy Rework
  even-more-fish-api/src/main/java/com/oheers/fish/api/economy/Economy.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/economy/EconomyType.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/Economy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/EMFCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/MoneyRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/GriefPreventionEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/PlayerPointsEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/VaultEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/SellGUI.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/SellHelper.java
  even-more-fish-plugin/src/main/resources/config.yml
  wiki/Economy.md
  wiki/_Sidebar.md
Labels: bug: fixed, optimizations (readability), optimizations (performance)

#503 Competition Config Rework
  even-more-fish-api/src/main/java/com/oheers/fish/api/FileUtil.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/Reward.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/EMFCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/AutoRunner.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Bar.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionQueue.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/MoneyRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/CompetitionConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/Messages.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/DatabaseV3.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/VaultEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/SellGUI.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/SellHelper.java
  even-more-fish-plugin/src/main/resources/competitions.yml
  even-more-fish-plugin/src/main/resources/competitions/_example.yml
  even-more-fish-plugin/src/main/resources/competitions/default-main.yml
  even-more-fish-plugin/src/main/resources/competitions/default-sunday1.yml
  even-more-fish-plugin/src/main/resources/competitions/default-sunday2.yml
  even-more-fish-plugin/src/main/resources/competitions/default-weekend.yml
  wiki/Competition-Configs.md
  wiki/_Sidebar.md
  wiki/competitions.yml.md
Labels: bug: fixed, suggestion (documentation): added, optimizations (readability), optimizations (performance)

#505 Prepare for Version 2.0.0
  README.md
  even-more-fish-api/build.gradle.kts
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/EMFRequirementsLoadEvent.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/RequirementType.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/EMFRewardEvent.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/EMFRewardsLoadEvent.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/Reward.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/Message.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/OldMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/FishManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/SellGUI.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
  settings.gradle.kts
  wiki/Home.md
Labels: bug: fixed, new feature, optimizations (readability), optimizations (performance)

#506 Add PlatformAdapters
  even-more-fish-api/src/main/java/com/oheers/fish/api/FileUtil.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/adapter/PlatformAdapter.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/plugin/EMFPlugin.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/Requirement.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/RequirementManager.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/Reward.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/RewardManager.java
  even-more-fish-paper/build.gradle.kts
  even-more-fish-paper/src/main/java/com/oheers/fish/adapter/PaperAdapter.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/adapter/SpigotAdapter.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
  settings.gradle.kts
Labels: optimizations (readability), optimizations (performance)

#509 Prevent config update if updates are disabled.
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
Labels: bug: fixed

#511 Update MiniMessage support to be sane.
  even-more-fish-api/src/main/java/com/oheers/fish/api/adapter/AbstractMessage.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/adapter/PlatformAdapter.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/plugin/EMFPlugin.java
  even-more-fish-paper/build.gradle.kts
  even-more-fish-paper/src/main/java/com/oheers/fish/adapter/PaperAdapter.java
  even-more-fish-paper/src/main/java/com/oheers/fish/adapter/PaperMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/SkullSaver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/UpdateChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/adapter/SpigotAdapter.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/adapter/SpigotMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/EMFCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Bar.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/MessageRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/Message.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/Messages.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/PrefixType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/migrate/LegacyToV3DatabaseMigration.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/GriefPreventionEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/PlayerPointsEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/VaultEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GUIUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/ApplyBaitsGUI.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/SellHelper.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemBuilder.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
Labels: optimizations (readability), optimizations (performance)

#513 Database
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/DataManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/DatabaseV3.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/connection/ConnectionFactory.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/model/CompetitionReport.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/model/FishReport.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/model/Transaction.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/model/UserReport.java
Labels: bug: fixed, optimizations (readability)

#521 Message Fixes
  even-more-fish-api/src/main/java/com/oheers/fish/api/adapter/AbstractMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/PrefixType.java
Labels: bug: fixed

#529 ItemMeta cleanup
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/SkullSaver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GUIUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemBuilder.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemUtils.java
Labels: optimizations (readability), optimizations (performance)

#530 Improve Bait Loading
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/BaitFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
Labels: optimizations (readability), optimizations (performance)

#532 Default config updates
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/FishConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityConversions.java
  even-more-fish-plugin/src/main/resources/competitions/defaults/main.yml
  even-more-fish-plugin/src/main/resources/competitions/defaults/sunday1.yml
  even-more-fish-plugin/src/main/resources/competitions/defaults/sunday2.yml
  even-more-fish-plugin/src/main/resources/competitions/defaults/weekend.yml
  even-more-fish-plugin/src/main/resources/rarities/defaults/common.yml
  even-more-fish-plugin/src/main/resources/rarities/defaults/epic.yml
  even-more-fish-plugin/src/main/resources/rarities/defaults/junk.yml
  even-more-fish-plugin/src/main/resources/rarities/defaults/legendary.yml
  even-more-fish-plugin/src/main/resources/rarities/defaults/rare.yml
Labels: bug: fixed, optimizations (readability)

#531 Fix HeadDatabase Addon
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/DenizenItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/EcoItemsItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/HeadDatabaseItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/ItemsAdderItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/OraxenItemAddon.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  settings.gradle.kts
Labels: bug: fixed, optimizations (readability)
