Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2024-11, with the labels that each got.

#489 Adds a "PR"able wiki
  .github/workflows/publish-wiki.yml
  wiki/Addons.md
  wiki/Biome-Sets.md
  wiki/Competition-Types.md
  wiki/Create-Addons.md
  wiki/Create-Reward-Types.md
  wiki/Developers.md
  wiki/FAQ.md
  wiki/FAQs.md
  wiki/Fish.yml.md
  wiki/Home.md
  wiki/Messages.yml.md
  wiki/Migrating-the-database.md
  wiki/Rarities.md
  wiki/Requirements.md
  wiki/Reward-Types.md
  wiki/_Footer.md
  wiki/_Sidebar.md
  wiki/competitions.yml.md
Labels: suggestion (plugin): added

#490 GitHub templates
  .github/PULL_REQUEST_TEMPLATE.yml
  .github/release.yml
Labels: suggestion (plugin): added

#494 Competition Strategy
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yml
  .github/release.yml
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/AddonManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionEntry.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionQueue.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/leaderboard/Leaderboard.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/NullStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  wiki/Messages.yml.md
Labels: suggestion (documentation): added, optimizations (readability), optimizations (performance)

#495 Update Wiki Stuff
  wiki/Addons.md
  wiki/Biome-Sets.md
  wiki/Competition-Types.md
  wiki/Create-Reward-Types.md
  wiki/FAQ.md
  wiki/FAQs.md
  wiki/Fish.yml.md
  wiki/Messages.yml.md
  wiki/Rarities.md
  wiki/Requirements.md
  wiki/_Footer.md
  wiki/_Sidebar.md
  wiki/competitions.yml.md
Labels: suggestion (documentation): added

#496 Added more freedom to the bossbar layout
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
Labels: bug: fixed
