Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-02, with the labels that each got.

#553 Fixes #498 & More bug fixes
  even-more-fish-addons-j17/build.gradle.kts
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/DenizenItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/EcoItemsItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/HeadDatabaseItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/ItemsAdderItemAddon.java
  even-more-fish-addons-j21/build.gradle.kts
  even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/NexoItemAddon.java
  even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/OraxenItemAddon.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/addons/Addon.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/AddonManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/Database.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
  even-more-fish-plugin/src/main/resources/config.yml
  settings.gradle.kts
  wiki/Addons.md
Labels: suggestion: documentation, bug: fixed, optimizations (readability), optimizations (performance)

#559 Code readability improvements & optimizations.
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
Labels: optimizations (readability), optimizations (performance)

#560 Respect leaderboard-count config
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/MessageConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/PrefixType.java
Labels: bug: fixed, optimizations (readability)

#570 Adds the ability for us to register custom recipes.
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/recipe/EMFShapedRecipe.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/recipe/EMFShapelessRecipe.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/recipe/RecipeUtil.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
Labels: new feature
