Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-08, with the labels that each got.

#762 Fix full-exit GUI action
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GuiUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/items/ItemFactory.java
Labels: bug: confirmed, bug: fixed

#777 Introduce an option to only override caught fish
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/resources/config.yml
Labels: suggestion (plugin): added, new feature

#781 Remove redundant `place-head-fish` config option
  even-more-fish-plugin/src/main/java/com/oheers/fish/SkullSaver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/resources/config.yml
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
Labels: optimizations (readability)

#786 Skip a help message if the description is empty
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/HelpMessageBuilder.java
Labels: suggestion: plugin, suggestion (plugin): added

#792 Don't open the GUI if no permission
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/MainCommand.java
  even-more-fish-plugin/src/main/resources/config.yml
Labels: bug: confirmed, bug: fixed

#796 Fixes an issue where baits could not be caught by default
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitHandler.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/manager/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
Labels: bug: fixed, optimizations (readability), optimizations (performance)
