Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-04, with the labels that each got.

#608 Fix empty lines in fish lore
  .github/PULL_REQUEST_TEMPLATE.md
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/PrefixType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
Labels: bug: confirmed, bug: fixed

#609 More Message Fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/NullStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
  even-more-fish-plugin/src/main/resources/locales/messages_cs.yml
  even-more-fish-plugin/src/main/resources/locales/messages_da.yml
  even-more-fish-plugin/src/main/resources/locales/messages_de.yml
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
  even-more-fish-plugin/src/main/resources/locales/messages_es.yml
  even-more-fish-plugin/src/main/resources/locales/messages_fr.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ja.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ko.yml
  even-more-fish-plugin/src/main/resources/locales/messages_nl.yml
  even-more-fish-plugin/src/main/resources/locales/messages_pl.yml
  even-more-fish-plugin/src/main/resources/locales/messages_pt-br.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ru.yml
  even-more-fish-plugin/src/main/resources/locales/messages_tr.yml
  even-more-fish-plugin/src/main/resources/locales/messages_vn.yml
  even-more-fish-plugin/src/main/resources/locales/messages_zh_cn.yml
  even-more-fish-plugin/src/main/resources/locales/messages_zh_tw.yml
Labels: bug: confirmed, bug: fixed

#612 Fix variable in the MOST_FISH leaderboard
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
Labels: bug: confirmed, bug: fixed

#614 EMFMessage empty message checks
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
Labels: bug: confirmed, bug: fixed

#615 Fix NPE in FishManager
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/FishManager.java
Labels: bug: confirmed, bug: fixed

#616 Fix messages not being sent
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/HelpMessageBuilder.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
Labels: bug: confirmed, bug: fixed

#618 Bait lore fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
Labels: bug: confirmed, bug: fixed

#619 Fix missing variable in competition join message
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
Labels: bug: confirmed, bug: fixed

#620 Fix two issues
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityFileUpdates.java
Labels: bug: confirmed, bug: fixed

#613 Reset config versions
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/GUIConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/GuiConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/GuiFillerConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MessageConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/HuntingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/ConfigGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GuiUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/ApplyBaitsGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/BaitsGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/MainMenuGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/SellGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/WorthNBT.java
  even-more-fish-plugin/src/main/resources/config.yml
  even-more-fish-plugin/src/main/resources/gui-fillers.yml
  even-more-fish-plugin/src/main/resources/guis.yml
  even-more-fish-plugin/src/main/resources/locales/messages_cs.yml
  even-more-fish-plugin/src/main/resources/locales/messages_da.yml
  even-more-fish-plugin/src/main/resources/locales/messages_de.yml
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
  even-more-fish-plugin/src/main/resources/locales/messages_es.yml
  even-more-fish-plugin/src/main/resources/locales/messages_fr.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ja.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ko.yml
  even-more-fish-plugin/src/main/resources/locales/messages_nl.yml
  even-more-fish-plugin/src/main/resources/locales/messages_pl.yml
  even-more-fish-plugin/src/main/resources/locales/messages_pt-br.yml
  even-more-fish-plugin/src/main/resources/locales/messages_ru.yml
  even-more-fish-plugin/src/main/resources/locales/messages_tr.yml
  even-more-fish-plugin/src/main/resources/locales/messages_vn.yml
  even-more-fish-plugin/src/main/resources/locales/messages_zh_cn.yml
  even-more-fish-plugin/src/main/resources/locales/messages_zh_tw.yml
Labels: bug: confirmed, bug: fixed

#623 Competition Fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/NullStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/FishManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
Labels: bug: confirmed, bug: fixed

#627 Fix GUI Issues
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/ConfigGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GuiUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemBuilder.java
  even-more-fish-plugin/src/main/resources/guis.yml
Labels: bug: confirmed, bug: fixed

#625 1.21.5 Support
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityFileUpdates.java
  settings.gradle.kts
Labels: dependencies

#630 Small addon update
  addons/even-more-fish-addons-j17/build.gradle.kts
  addons/even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/DenizenItemAddon.java
  addons/even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/EcoItemsItemAddon.java
  addons/even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/HeadDatabaseItemAddon.java
  addons/even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/ItemsAdderItemAddon.java
  addons/even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/J17AddonLoader.java
  addons/even-more-fish-addons-j21/build.gradle.kts
  addons/even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/CraftEngineItemAddon.java
  addons/even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/J21AddonLoader.java
  addons/even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/NexoItemAddon.java
  addons/even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/OraxenItemAddon.java
  buildSrc/src/main/kotlin/com.oheers.evenmorefish.java-conventions.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/DefaultAddons.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  settings.gradle.kts
Labels: optimizations (readability)

#635 Fix addons in dev builds
  settings.gradle.kts
Labels: bug: confirmed, bug: fixed

#636 Fixes issue with addons build
  buildSrc/src/main/kotlin/com.oheers.evenmorefish.java-conventions.gradle.kts
  even-more-fish-plugin/build.gradle.kts
Labels: bug: fixed

#638 Add MiniMessage converter exclusions
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
Labels: bug: confirmed, bug: fixed
