Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-05, with the labels that each got.

#639 Message Updates
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/configs/BaitFileUpdates.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/MainCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFileUpdates.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/ApplyBaitsGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
  even-more-fish-plugin/src/main/resources/baits/_example.yml
  even-more-fish-plugin/src/main/resources/baits/fresh-water.yml
  even-more-fish-plugin/src/main/resources/baits/shrimp.yml
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
Labels: bug: confirmed, bug: fixed, optimizations (readability)

#642 Fix Specific Fish and Specific Rarity competitions
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
Labels: bug: confirmed, bug: fixed

#646 Fix a few bugs
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/configs/BaitConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/NullStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/FishConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/Logging.java
Labels: bug: confirmed, bug: fixed

#652 2.0.0-RC3
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/api/EMFFishHuntEvent.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/Database.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/data/FishRarityKey.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/EMFFishListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/HuntingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GuiUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/FishJournalGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/SellGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/WorthNBT.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/nbt/NbtUtils.java
  even-more-fish-plugin/src/main/resources/config.yml
  even-more-fish-plugin/src/main/resources/guis.yml
  gradle.properties
  wiki/Catch-Types.md
  wiki/Placeholders.md
  wiki/_Sidebar.md
Labels: bug: confirmed, bug: fixed, suggestion (plugin): added, suggestion (documentation): added

#653 Placeholder refactor and cleanup
  even-more-fish-plugin/src/main/java/com/oheers/fish/placeholders/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/resources/placeholders.yml
Labels: after 2.0

#666 GUI back fix
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GuiUtils.java
Labels: bug: confirmed, bug: fixed
