Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-07, with the labels that each got.

#726 1.21.7
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  settings.gradle.kts
Labels: dependencies

#727 Fix infinite bait exception
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
Labels: bug: confirmed, bug: fixed

#728 Fix comp bossbar and join message
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/plugin/EventManager.java
Labels: bug: confirmed, bug: fixed

#731 Update some things
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/rods/RodConversion.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/FishJournalGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
Labels: bug: confirmed, bug: fixed, optimizations (readability)

#749 Fix "no addons" bug on linux machines
  even-more-fish-api/src/main/java/com/oheers/fish/api/FileUtil.java
Labels: bug: fixed

#756 Fix requirements
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
Labels: bug: confirmed, bug: fixed
