Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-03, with the labels that each got.

#579 Adds support for CraftEngine
  even-more-fish-addons-j21/build.gradle.kts
  even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/CraftEngineItemAddon.java
  even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/NexoItemAddon.java
  even-more-fish-addons-j21/src/main/java/com/oheers/evenmorefish/addons/OraxenItemAddon.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/DefaultCatalog.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/DefaultSchema.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/Keys.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/Tables.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/Competitions.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/Fish.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/FishLog.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/Transactions.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/Users.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/UsersSales.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/CompetitionsRecord.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/FishLogRecord.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/FishRecord.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/TransactionsRecord.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/UsersRecord.java
  even-more-fish-plugin/src/main/generated/com/oheers/fish/database/generated/mysql/tables/records/UsersSalesRecord.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  settings.gradle.kts
  wiki/Addons.md
Labels: suggestion (documentation): added, new feature

#582 Bait Config Rework
  README.md
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/configs/BaitConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/BaitFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/exceptions/MaxBaitReachedException.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityConversions.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/ApplyBaitsGUI.java
  even-more-fish-plugin/src/main/resources/baits.yml
  even-more-fish-plugin/src/main/resources/baits/_example.yml
  even-more-fish-plugin/src/main/resources/baits/epic-elixir.yml
  even-more-fish-plugin/src/main/resources/baits/fresh-water.yml
  even-more-fish-plugin/src/main/resources/baits/infinite-bait.yml
  even-more-fish-plugin/src/main/resources/baits/legendary-lure.yml
  even-more-fish-plugin/src/main/resources/baits/shrimp.yml
  even-more-fish-plugin/src/main/resources/baits/stringy-worms.yml
  even-more-fish-plugin/src/main/resources/config.yml
  even-more-fish-plugin/src/main/resources/locales/messages_en.yml
  wiki/Baits.md
  wiki/FAQs.md
  wiki/_Sidebar.md
Labels: optimizations (readability), optimizations (performance)

#586 Backports fixes to the 1.7.x branch
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/ItemsAdderItemAddon.java
  even-more-fish-addons-j17/src/main/java/com/oheers/evenmorefish/addons/OraxenItemAddon.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/SellHelper.java
  settings.gradle.kts
Labels: bug: fixed, optimizations (readability), optimizations (performance)

#588 Create Weights-System.md
  wiki/Weights-System.md
Labels: suggestion (documentation): added

#593 Allow subcommands to be configured
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/MainCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/resources/config.yml
Labels: new feature

#589 Reworks baited rod lore
  even-more-fish-api/src/main/java/com/oheers/fish/api/economy/Economy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/GUIUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/nbt/NbtKeys.java
Labels: bug: fixed, optimizations (readability), optimizations (performance)

#590 Slight rework of RewardType and RequirementType
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/EMFRequirementsLoadEvent.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/Requirement.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/RequirementManager.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/requirement/RequirementType.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/EMFRewardsLoadEvent.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/Reward.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/RewardManager.java
  even-more-fish-api/src/main/java/com/oheers/fish/api/reward/RewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/CommandRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/EXPRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/EffectRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/HealthRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/HungerRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/ItemRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/MessageRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/AuraSkillsXPRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/GPClaimBlocksRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/McMMOXPRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/MoneyRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/PermissionRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/external/PlayerPointsRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/BiomeRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/BiomeSetRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/DisabledRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/GroupRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/IRLTimeRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/InGameTimeRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/MoonPhaseRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/NearbyPlayersRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/PermissionRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/RegionRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/WeatherRequirementType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/requirements/WorldRequirementType.java
  wiki/Create-Reward-Types.md
Labels: optimizations (readability), optimizations (performance)

#592 Improve rarity configs
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/leaderboard/Leaderboard.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/config/RarityFileUpdates.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFMessage.java
  even-more-fish-plugin/src/main/resources/rarities/_example.yml
  even-more-fish-plugin/src/main/resources/rarities/common.yml
  even-more-fish-plugin/src/main/resources/rarities/epic.yml
  even-more-fish-plugin/src/main/resources/rarities/junk.yml
  even-more-fish-plugin/src/main/resources/rarities/legendary.yml
  even-more-fish-plugin/src/main/resources/rarities/rare.yml
Labels: optimizations (readability)

#595 Adds the ability to disable catching specific baits
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/resources/baits/_example.yml
Labels: new feature

#600 Add some protection for EMF items
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/AntiCraft.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemProtectionListener.java
  even-more-fish-plugin/src/main/resources/config.yml
Labels: bug: confirmed, bug: fixed

#601 Fix raw-material
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
Labels: bug: confirmed, bug: fixed

#603 Possible ItemAddon fix
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/AddonManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
Labels: bug: unconfirmed, bug: fixed

#604 Add maven repository information to the wiki
  wiki/Developers.md
Labels: suggestion: documentation, suggestion (documentation): added

#594 Back messages with Components
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitListener.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/BaitNBTManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/HelpMessageBuilder.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/MainCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Bar.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/JoinChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/leaderboard/Leaderboard.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/rewardtypes/MessageRewardType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/RandomStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/ConfigBase.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MessageConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/migrate/LegacyToV3DatabaseMigration.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/GriefPreventionEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/PlayerPointsEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/economy/VaultEconomyType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Rarity.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/ConfigGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/ApplyBaitsGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/ConfigMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/PrefixType.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/selling/SellHelper.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemBuilder.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
Labels: optimizations (readability), optimizations (performance)

#599 Set the minimum version to 1.20
  LICENSE
  README.md
  even-more-fish-api/src/main/java/com/oheers/fish/api/addons/exceptions/JavaVersionException.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/UpdateChecker.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/commands/AdminCommand.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  settings.gradle.kts
Labels: optimizations (performance), dependencies

#605 Fix ItemFactory lore
  even-more-fish-api/src/main/java/com/oheers/fish/api/addons/exceptions/JavaVersionException.java
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/AddonManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/ConfigGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemFactory.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/ItemProtectionListener.java
Labels: bug: confirmed, bug: fixed

#607 Fish lore Fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/Fish.java
Labels: bug: confirmed, bug: fixed
