Repository EvenMoreFish/EvenMoreFish, pull requests merged in 2025-06, with the labels that each got.

#669 Message Update
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFListMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/EMFSingleMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
Labels: bug: unconfirmed, bug: fixed

#671 Fix Journal Items
  even-more-fish-plugin/src/main/java/com/oheers/fish/items/ItemFactory.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/items/configs/ItemConfig.java
Labels: bug: confirmed, bug: fixed

#691 NPE Fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Competition.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/FishingProcessor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/Processor.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/FishManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/FishJournalGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/utils/WeightedRandom.java
Labels: bug: confirmed, bug: fixed

#697 Bug Fixes
  even-more-fish-plugin/src/main/java/com/oheers/fish/EvenMoreFish.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/FishUtils.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/addons/InternalAddonLoader.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/baits/Bait.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/Bar.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/CompetitionEntry.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/configs/CompetitionFile.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/LargestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/MostFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/ShortestTotalStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificFishStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/competition/strategies/SpecificRarityStrategy.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/config/MainConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/fishing/items/FishManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/ConfigGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/gui/guis/FishJournalGui.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/items/configs/UnbreakableItemConfig.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/messages/abstracted/EMFMessage.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/placeholders/PlaceholderReceiver.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/plugin/DependencyManager.java
  even-more-fish-plugin/src/main/java/com/oheers/fish/plugin/PluginDataManager.java
  even-more-fish-plugin/src/test/java/com/oheers/fish/utils/WeightedRandomTest.java
Labels: bug: confirmed, bug: fixed

#715 Fixes various build issues
  even-more-fish-plugin/build.gradle.kts
  even-more-fish-plugin/src/main/java/com/oheers/fish/database/Database.java
  renovate.json
  settings.gradle.kts
Labels: WTD
